// Сгенерировано Scripts/generate_seed.py из starter-data.md — не править вручную.
// Продуктов: 49, рецептов: 40.

import Foundation

enum SeedData {

    static let products: [SeedProduct] = [
        SeedProduct(name: "Куриное филе", category: "Мясо", unit: "г", gramsPerUnit: 1,
                    caloriesPer100: 165, proteinPer100: 31, fatPer100: 3.6, carbsPer100: 0,
                    lowStockThreshold: 200, initialAmount: 500, currentAmount: 230,
                    shelfLifeDays: 5, purchasedDaysAgo: 2),
        SeedProduct(name: "Говяжий фарш (15% жирности)", category: "Мясо", unit: "г", gramsPerUnit: 1,
                    caloriesPer100: 215, proteinPer100: 18, fatPer100: 15, carbsPer100: 0,
                    lowStockThreshold: 200, initialAmount: 400, currentAmount: 376,
                    shelfLifeDays: 5, purchasedDaysAgo: 1),
        SeedProduct(name: "Свинина (шея)", category: "Мясо", unit: "г", gramsPerUnit: 1,
                    caloriesPer100: 260, proteinPer100: 16, fatPer100: 21, carbsPer100: 0,
                    lowStockThreshold: 200, initialAmount: 600, currentAmount: 342,
                    shelfLifeDays: 5, purchasedDaysAgo: 1),
        SeedProduct(name: "Яйца куриные", category: "Молочка/яйца", unit: "шт", gramsPerUnit: 55,
                    caloriesPer100: 155, proteinPer100: 13, fatPer100: 11, carbsPer100: 1.1,
                    lowStockThreshold: 3, initialAmount: 10, currentAmount: 9,
                    shelfLifeDays: 28, purchasedDaysAgo: 3),
        SeedProduct(name: "Молоко 2.5%", category: "Молочка", unit: "мл", gramsPerUnit: 1,
                    caloriesPer100: 52, proteinPer100: 2.8, fatPer100: 2.5, carbsPer100: 4.7,
                    lowStockThreshold: 250, initialAmount: 900, currentAmount: 120,
                    shelfLifeDays: 14, purchasedDaysAgo: 1),
        SeedProduct(name: "Творог 5%", category: "Молочка", unit: "г", gramsPerUnit: 1,
                    caloriesPer100: 121, proteinPer100: 17, fatPer100: 5, carbsPer100: 3,
                    lowStockThreshold: 100, initialAmount: 400, currentAmount: 180,
                    shelfLifeDays: 14, purchasedDaysAgo: 0),
        SeedProduct(name: "Сыр твёрдый (голландский)", category: "Молочка", unit: "г", gramsPerUnit: 1,
                    caloriesPer100: 352, proteinPer100: 26, fatPer100: 27, carbsPer100: 0,
                    lowStockThreshold: 100, initialAmount: 500, currentAmount: 285,
                    shelfLifeDays: 14, purchasedDaysAgo: 0),
        SeedProduct(name: "Сливочное масло", category: "Молочка", unit: "г", gramsPerUnit: 1,
                    caloriesPer100: 748, proteinPer100: 0.5, fatPer100: 82.5, carbsPer100: 0.8,
                    lowStockThreshold: 100, initialAmount: 500, currentAmount: 60,
                    shelfLifeDays: 14, purchasedDaysAgo: 0),
        SeedProduct(name: "Рис (сухой)", category: "Крупы", unit: "г", gramsPerUnit: 1,
                    caloriesPer100: 344, proteinPer100: 6.7, fatPer100: 0.7, carbsPer100: 78,
                    lowStockThreshold: 200, initialAmount: 1000, currentAmount: 870,
                    shelfLifeDays: nil, purchasedDaysAgo: 1),
        SeedProduct(name: "Гречка (сухая)", category: "Крупы", unit: "г", gramsPerUnit: 1,
                    caloriesPer100: 313, proteinPer100: 12.6, fatPer100: 3.3, carbsPer100: 62,
                    lowStockThreshold: 200, initialAmount: 1000, currentAmount: 350,
                    shelfLifeDays: nil, purchasedDaysAgo: 4),
        SeedProduct(name: "Макароны (сухие)", category: "Крупы", unit: "г", gramsPerUnit: 1,
                    caloriesPer100: 337, proteinPer100: 10.4, fatPer100: 1.3, carbsPer100: 71,
                    lowStockThreshold: 200, initialAmount: 500, currentAmount: 405,
                    shelfLifeDays: nil, purchasedDaysAgo: 3),
        SeedProduct(name: "Картофель", category: "Овощи", unit: "г", gramsPerUnit: 1,
                    caloriesPer100: 77, proteinPer100: 2, fatPer100: 0.4, carbsPer100: 16.3,
                    lowStockThreshold: 150, initialAmount: 700, currentAmount: 301,
                    shelfLifeDays: 21, purchasedDaysAgo: 6),
        SeedProduct(name: "Морковь", category: "Овощи", unit: "г", gramsPerUnit: 1,
                    caloriesPer100: 41, proteinPer100: 0.9, fatPer100: 0.2, carbsPer100: 9.6,
                    lowStockThreshold: 150, initialAmount: 700, currentAmount: 231,
                    shelfLifeDays: 21, purchasedDaysAgo: 5),
        SeedProduct(name: "Лук репчатый", category: "Овощи", unit: "г", gramsPerUnit: 1,
                    caloriesPer100: 40, proteinPer100: 1.1, fatPer100: 0, carbsPer100: 9.3,
                    lowStockThreshold: 150, initialAmount: 500, currentAmount: 210,
                    shelfLifeDays: 21, purchasedDaysAgo: 0),
        SeedProduct(name: "Чеснок", category: "Овощи", unit: "г", gramsPerUnit: 1,
                    caloriesPer100: 149, proteinPer100: 6.5, fatPer100: 0.5, carbsPer100: 33,
                    lowStockThreshold: 150, initialAmount: 300, currentAmount: 165,
                    shelfLifeDays: 21, purchasedDaysAgo: 4),
        SeedProduct(name: "Помидоры", category: "Овощи", unit: "г", gramsPerUnit: 1,
                    caloriesPer100: 20, proteinPer100: 0.9, fatPer100: 0.2, carbsPer100: 3.9,
                    lowStockThreshold: 150, initialAmount: 700, currentAmount: 525,
                    shelfLifeDays: 21, purchasedDaysAgo: 4),
        SeedProduct(name: "Огурцы", category: "Овощи", unit: "г", gramsPerUnit: 1,
                    caloriesPer100: 15, proteinPer100: 0.8, fatPer100: 0.1, carbsPer100: 2.8,
                    lowStockThreshold: 150, initialAmount: 700, currentAmount: 511,
                    shelfLifeDays: 21, purchasedDaysAgo: 0),
        SeedProduct(name: "Болгарский перец", category: "Овощи", unit: "г", gramsPerUnit: 1,
                    caloriesPer100: 27, proteinPer100: 1, fatPer100: 0.3, carbsPer100: 6,
                    lowStockThreshold: 150, initialAmount: 1000, currentAmount: 660,
                    shelfLifeDays: 21, purchasedDaysAgo: 2),
        SeedProduct(name: "Капуста белокочанная", category: "Овощи", unit: "г", gramsPerUnit: 1,
                    caloriesPer100: 25, proteinPer100: 1.8, fatPer100: 0.1, carbsPer100: 4.7,
                    lowStockThreshold: 150, initialAmount: 300, currentAmount: 210,
                    shelfLifeDays: 21, purchasedDaysAgo: 4),
        SeedProduct(name: "Лимон", category: "Фрукты", unit: "шт", gramsPerUnit: 100,
                    caloriesPer100: 29, proteinPer100: 0.9, fatPer100: 0.1, carbsPer100: 9.3,
                    lowStockThreshold: 2, initialAmount: 4, currentAmount: 2.5,
                    shelfLifeDays: 21, purchasedDaysAgo: 0),
        SeedProduct(name: "Яблоко", category: "Фрукты", unit: "шт", gramsPerUnit: 180,
                    caloriesPer100: 47, proteinPer100: 0.4, fatPer100: 0.4, carbsPer100: 9.8,
                    lowStockThreshold: 2, initialAmount: 4, currentAmount: 2.8,
                    shelfLifeDays: 21, purchasedDaysAgo: 6),
        SeedProduct(name: "Растительное масло", category: "Масла", unit: "мл", gramsPerUnit: 1,
                    caloriesPer100: 899, proteinPer100: 0, fatPer100: 99.9, carbsPer100: 0,
                    lowStockThreshold: 250, initialAmount: 500, currentAmount: 460,
                    shelfLifeDays: nil, purchasedDaysAgo: 6),
        SeedProduct(name: "Соль", category: "Специи", unit: "г", gramsPerUnit: 1,
                    caloriesPer100: 0, proteinPer100: 0, fatPer100: 0, carbsPer100: 0,
                    lowStockThreshold: 200, initialAmount: 500, currentAmount: 365,
                    shelfLifeDays: nil, purchasedDaysAgo: 0),
        SeedProduct(name: "Сахар", category: "Специи", unit: "г", gramsPerUnit: 1,
                    caloriesPer100: 398, proteinPer100: 0, fatPer100: 0, carbsPer100: 99.8,
                    lowStockThreshold: 200, initialAmount: 500, currentAmount: 470,
                    shelfLifeDays: nil, purchasedDaysAgo: 0),
        SeedProduct(name: "Мука пшеничная", category: "Бакалея", unit: "г", gramsPerUnit: 1,
                    caloriesPer100: 334, proteinPer100: 10.3, fatPer100: 1.1, carbsPer100: 68.9,
                    lowStockThreshold: 250, initialAmount: 1000, currentAmount: 920,
                    shelfLifeDays: nil, purchasedDaysAgo: 3),
        SeedProduct(name: "Соевый соус", category: "Соусы", unit: "мл", gramsPerUnit: 1,
                    caloriesPer100: 60, proteinPer100: 6, fatPer100: 0, carbsPer100: 9.6,
                    lowStockThreshold: 80, initialAmount: 300, currentAmount: 186,
                    shelfLifeDays: nil, purchasedDaysAgo: 2),
        SeedProduct(name: "Майонез", category: "Соусы", unit: "г", gramsPerUnit: 1,
                    caloriesPer100: 627, proteinPer100: 1, fatPer100: 67, carbsPer100: 2.6,
                    lowStockThreshold: 100, initialAmount: 500, currentAmount: 335,
                    shelfLifeDays: nil, purchasedDaysAgo: 6),
        SeedProduct(name: "Зелёный лук", category: "Зелень", unit: "г", gramsPerUnit: 1,
                    caloriesPer100: 19, proteinPer100: 1.3, fatPer100: 0, carbsPer100: 3.5,
                    lowStockThreshold: 20, initialAmount: 50, currentAmount: 33,
                    shelfLifeDays: 7, purchasedDaysAgo: 1),
        SeedProduct(name: "Укроп", category: "Зелень", unit: "г", gramsPerUnit: 1,
                    caloriesPer100: 43, proteinPer100: 2.5, fatPer100: 0.5, carbsPer100: 6.3,
                    lowStockThreshold: 20, initialAmount: 50, currentAmount: 8,
                    shelfLifeDays: 7, purchasedDaysAgo: 5),
        SeedProduct(name: "Хлеб пшеничный", category: "Хлеб", unit: "г", gramsPerUnit: 1,
                    caloriesPer100: 265, proteinPer100: 8.1, fatPer100: 3.2, carbsPer100: 48.8,
                    lowStockThreshold: 120, initialAmount: 500, currentAmount: 155,
                    shelfLifeDays: 6, purchasedDaysAgo: 4),
        SeedProduct(name: "Фарш свиной", category: "Мясо", unit: "г", gramsPerUnit: 1,
                    caloriesPer100: 263, proteinPer100: 16, fatPer100: 21, carbsPer100: 0,
                    lowStockThreshold: 200, initialAmount: 800, currentAmount: 320,
                    shelfLifeDays: 5, purchasedDaysAgo: 1),
        SeedProduct(name: "Фарш свино-говяжий (50/50)", category: "Мясо", unit: "г", gramsPerUnit: 1,
                    caloriesPer100: 230, proteinPer100: 17, fatPer100: 18, carbsPer100: 0,
                    lowStockThreshold: 200, initialAmount: 600, currentAmount: 486,
                    shelfLifeDays: 5, purchasedDaysAgo: 1),
        SeedProduct(name: "Сыр Дор Блю (голубой)", category: "Молочка", unit: "г", gramsPerUnit: 1,
                    caloriesPer100: 353, proteinPer100: 21, fatPer100: 29, carbsPer100: 0,
                    lowStockThreshold: 100, initialAmount: 300, currentAmount: 0,
                    shelfLifeDays: 14, purchasedDaysAgo: 0),
        SeedProduct(name: "Сыр сливочный (крем-сыр)", category: "Молочка", unit: "г", gramsPerUnit: 1,
                    caloriesPer100: 253, proteinPer100: 5, fatPer100: 24, carbsPer100: 4,
                    lowStockThreshold: 100, initialAmount: 200, currentAmount: 152,
                    shelfLifeDays: 14, purchasedDaysAgo: 1),
        SeedProduct(name: "Сыр плавленый", category: "Молочка", unit: "г", gramsPerUnit: 1,
                    caloriesPer100: 257, proteinPer100: 10, fatPer100: 21, carbsPer100: 5,
                    lowStockThreshold: 100, initialAmount: 200, currentAmount: 112,
                    shelfLifeDays: 14, purchasedDaysAgo: 0),
        SeedProduct(name: "Говяжья вырезка (без жира)", category: "Мясо", unit: "г", gramsPerUnit: 1,
                    caloriesPer100: 158, proteinPer100: 21, fatPer100: 8, carbsPer100: 0,
                    lowStockThreshold: 200, initialAmount: 500, currentAmount: 455,
                    shelfLifeDays: 5, purchasedDaysAgo: 3),
        SeedProduct(name: "Куриные бёдра", category: "Мясо", unit: "г", gramsPerUnit: 1,
                    caloriesPer100: 185, proteinPer100: 17, fatPer100: 13, carbsPer100: 0,
                    lowStockThreshold: 200, initialAmount: 800, currentAmount: 616,
                    shelfLifeDays: 5, purchasedDaysAgo: 0),
        SeedProduct(name: "Куриные окорочка", category: "Мясо", unit: "г", gramsPerUnit: 1,
                    caloriesPer100: 185, proteinPer100: 17, fatPer100: 13, carbsPer100: 0,
                    lowStockThreshold: 200, initialAmount: 800, currentAmount: 352,
                    shelfLifeDays: 5, purchasedDaysAgo: 2),
        SeedProduct(name: "Куриная голень", category: "Мясо", unit: "г", gramsPerUnit: 1,
                    caloriesPer100: 160, proteinPer100: 19, fatPer100: 8.7, carbsPer100: 0,
                    lowStockThreshold: 200, initialAmount: 800, currentAmount: 696,
                    shelfLifeDays: 5, purchasedDaysAgo: 0),
        SeedProduct(name: "Салат Айсберг", category: "Овощи", unit: "г", gramsPerUnit: 1,
                    caloriesPer100: 14, proteinPer100: 0.9, fatPer100: 0.1, carbsPer100: 3,
                    lowStockThreshold: 150, initialAmount: 1000, currentAmount: 790,
                    shelfLifeDays: 21, purchasedDaysAgo: 1),
        SeedProduct(name: "Хлеб чёрный (ржаной)", category: "Хлеб", unit: "г", gramsPerUnit: 1,
                    caloriesPer100: 214, proteinPer100: 6.6, fatPer100: 1.2, carbsPer100: 40.7,
                    lowStockThreshold: 120, initialAmount: 300, currentAmount: 255,
                    shelfLifeDays: 6, purchasedDaysAgo: 4),
        SeedProduct(name: "Хлеб Бородинский", category: "Хлеб", unit: "г", gramsPerUnit: 1,
                    caloriesPer100: 208, proteinPer100: 6.8, fatPer100: 1.3, carbsPer100: 39.9,
                    lowStockThreshold: 120, initialAmount: 400, currentAmount: 144,
                    shelfLifeDays: 6, purchasedDaysAgo: 1),
        SeedProduct(name: "Форель охлаждённая", category: "Рыба", unit: "г", gramsPerUnit: 1,
                    caloriesPer100: 150, proteinPer100: 20, fatPer100: 7, carbsPer100: 0,
                    lowStockThreshold: 150, initialAmount: 500, currentAmount: 0,
                    shelfLifeDays: 3, purchasedDaysAgo: 0),
        SeedProduct(name: "Креветки (очищенные)", category: "Морепродукты", unit: "г", gramsPerUnit: 1,
                    caloriesPer100: 95, proteinPer100: 19, fatPer100: 1.7, carbsPer100: 0.2,
                    lowStockThreshold: 150, initialAmount: 400, currentAmount: 0,
                    shelfLifeDays: 4, purchasedDaysAgo: 0),
        SeedProduct(name: "Огурцы маринованные", category: "Овощи", unit: "г", gramsPerUnit: 1,
                    caloriesPer100: 16, proteinPer100: 0.8, fatPer100: 0.1, carbsPer100: 2.7,
                    lowStockThreshold: 150, initialAmount: 500, currentAmount: 0,
                    shelfLifeDays: 21, purchasedDaysAgo: 0),
        SeedProduct(name: "Кетчуп", category: "Соусы", unit: "г", gramsPerUnit: 1,
                    caloriesPer100: 100, proteinPer100: 1.8, fatPer100: 0.1, carbsPer100: 25,
                    lowStockThreshold: 100, initialAmount: 500, currentAmount: 40,
                    shelfLifeDays: nil, purchasedDaysAgo: 2),
        SeedProduct(name: "Лаваш/пита", category: "Хлеб", unit: "г", gramsPerUnit: 1,
                    caloriesPer100: 275, proteinPer100: 9, fatPer100: 1.2, carbsPer100: 55,
                    lowStockThreshold: 120, initialAmount: 300, currentAmount: 0,
                    shelfLifeDays: 6, purchasedDaysAgo: 0),
        SeedProduct(name: "Индейка (филе грудки)", category: "Мясо", unit: "г", gramsPerUnit: 1,
                    caloriesPer100: 84, proteinPer100: 19.2, fatPer100: 0.7, carbsPer100: 0,
                    lowStockThreshold: 200, initialAmount: 400, currentAmount: 364,
                    shelfLifeDays: 5, purchasedDaysAgo: 3),
        SeedProduct(name: "Индейка (бедро)", category: "Мясо", unit: "г", gramsPerUnit: 1,
                    caloriesPer100: 144, proteinPer100: 20.5, fatPer100: 6.7, carbsPer100: 0,
                    lowStockThreshold: 200, initialAmount: 400, currentAmount: 0,
                    shelfLifeDays: 5, purchasedDaysAgo: 0),
    ]

    static let recipes: [SeedRecipe] = [
        SeedRecipe(name: "Омлет классический", cookingTimeMinutes: 10, baseServings: 2, ingredients: [
            SeedIngredient(product: "Яйца куриные", amountPerBaseServing: 3),
            SeedIngredient(product: "Молоко 2.5%", amountPerBaseServing: 50),
            SeedIngredient(product: "Сливочное масло", amountPerBaseServing: 10),
            SeedIngredient(product: "Соль", amountPerBaseServing: 2),
        ]),
        SeedRecipe(name: "Гречка с курицей", cookingTimeMinutes: 30, baseServings: 2, ingredients: [
            SeedIngredient(product: "Гречка (сухая)", amountPerBaseServing: 150),
            SeedIngredient(product: "Куриное филе", amountPerBaseServing: 300),
            SeedIngredient(product: "Лук репчатый", amountPerBaseServing: 50),
            SeedIngredient(product: "Морковь", amountPerBaseServing: 50),
            SeedIngredient(product: "Растительное масло", amountPerBaseServing: 20),
            SeedIngredient(product: "Соль", amountPerBaseServing: 3),
        ]),
        SeedRecipe(name: "Куриный суп с рисом", cookingTimeMinutes: 40, baseServings: 2, ingredients: [
            SeedIngredient(product: "Куриное филе", amountPerBaseServing: 250),
            SeedIngredient(product: "Рис (сухой)", amountPerBaseServing: 60),
            SeedIngredient(product: "Картофель", amountPerBaseServing: 200),
            SeedIngredient(product: "Морковь", amountPerBaseServing: 50),
            SeedIngredient(product: "Лук репчатый", amountPerBaseServing: 40),
            SeedIngredient(product: "Соль", amountPerBaseServing: 5),
        ]),
        SeedRecipe(name: "Паста с чесноком и маслом (Aglio e Olio)", cookingTimeMinutes: 15, baseServings: 2, ingredients: [
            SeedIngredient(product: "Макароны (сухие)", amountPerBaseServing: 200),
            SeedIngredient(product: "Чеснок", amountPerBaseServing: 15),
            SeedIngredient(product: "Растительное масло", amountPerBaseServing: 40),
            SeedIngredient(product: "Соль", amountPerBaseServing: 3),
            SeedIngredient(product: "Укроп", amountPerBaseServing: 5),
        ]),
        SeedRecipe(name: "Овощной салат", cookingTimeMinutes: 10, baseServings: 2, ingredients: [
            SeedIngredient(product: "Помидоры", amountPerBaseServing: 150),
            SeedIngredient(product: "Огурцы", amountPerBaseServing: 150),
            SeedIngredient(product: "Болгарский перец", amountPerBaseServing: 100),
            SeedIngredient(product: "Зелёный лук", amountPerBaseServing: 20),
            SeedIngredient(product: "Растительное масло", amountPerBaseServing: 20),
            SeedIngredient(product: "Соль", amountPerBaseServing: 2),
        ]),
        SeedRecipe(name: "Жареная картошка с луком", cookingTimeMinutes: 25, baseServings: 2, ingredients: [
            SeedIngredient(product: "Картофель", amountPerBaseServing: 400),
            SeedIngredient(product: "Лук репчатый", amountPerBaseServing: 80),
            SeedIngredient(product: "Растительное масло", amountPerBaseServing: 40),
            SeedIngredient(product: "Соль", amountPerBaseServing: 4),
        ]),
        SeedRecipe(name: "Творожная запеканка", cookingTimeMinutes: 40, baseServings: 2, ingredients: [
            SeedIngredient(product: "Творог 5%", amountPerBaseServing: 400),
            SeedIngredient(product: "Яйца куриные", amountPerBaseServing: 2),
            SeedIngredient(product: "Сахар", amountPerBaseServing: 40),
            SeedIngredient(product: "Мука пшеничная", amountPerBaseServing: 40),
        ]),
        SeedRecipe(name: "Бутерброд с сыром", cookingTimeMinutes: 5, baseServings: 2, ingredients: [
            SeedIngredient(product: "Хлеб пшеничный", amountPerBaseServing: 60),
            SeedIngredient(product: "Сыр твёрдый (голландский)", amountPerBaseServing: 40),
            SeedIngredient(product: "Сливочное масло", amountPerBaseServing: 10),
        ]),
        SeedRecipe(name: "Свинина жареная с луком", cookingTimeMinutes: 25, baseServings: 2, ingredients: [
            SeedIngredient(product: "Свинина (шея)", amountPerBaseServing: 350),
            SeedIngredient(product: "Лук репчатый", amountPerBaseServing: 100),
            SeedIngredient(product: "Растительное масло", amountPerBaseServing: 20),
            SeedIngredient(product: "Соль", amountPerBaseServing: 4),
        ]),
        SeedRecipe(name: "Говяжьи котлеты", cookingTimeMinutes: 30, baseServings: 2, ingredients: [
            SeedIngredient(product: "Говяжий фарш (15% жирности)", amountPerBaseServing: 400),
            SeedIngredient(product: "Лук репчатый", amountPerBaseServing: 50),
            SeedIngredient(product: "Яйца куриные", amountPerBaseServing: 1),
            SeedIngredient(product: "Соль", amountPerBaseServing: 3),
            SeedIngredient(product: "Растительное масло", amountPerBaseServing: 20),
        ]),
        SeedRecipe(name: "Салат из капусты", cookingTimeMinutes: 10, baseServings: 2, ingredients: [
            SeedIngredient(product: "Капуста белокочанная", amountPerBaseServing: 250),
            SeedIngredient(product: "Морковь", amountPerBaseServing: 50),
            SeedIngredient(product: "Растительное масло", amountPerBaseServing: 20),
            SeedIngredient(product: "Соль", amountPerBaseServing: 3),
        ]),
        SeedRecipe(name: "Рис с овощами", cookingTimeMinutes: 25, baseServings: 2, ingredients: [
            SeedIngredient(product: "Рис (сухой)", amountPerBaseServing: 150),
            SeedIngredient(product: "Морковь", amountPerBaseServing: 50),
            SeedIngredient(product: "Болгарский перец", amountPerBaseServing: 80),
            SeedIngredient(product: "Лук репчатый", amountPerBaseServing: 40),
            SeedIngredient(product: "Растительное масло", amountPerBaseServing: 20),
            SeedIngredient(product: "Соевый соус", amountPerBaseServing: 20),
        ]),
        SeedRecipe(name: "Яичница с помидорами", cookingTimeMinutes: 10, baseServings: 2, ingredients: [
            SeedIngredient(product: "Яйца куриные", amountPerBaseServing: 3),
            SeedIngredient(product: "Помидоры", amountPerBaseServing: 150),
            SeedIngredient(product: "Растительное масло", amountPerBaseServing: 15),
            SeedIngredient(product: "Соль", amountPerBaseServing: 2),
        ]),
        SeedRecipe(name: "Куриные наггетсы (простые, без панировки)", cookingTimeMinutes: 25, baseServings: 2, ingredients: [
            SeedIngredient(product: "Куриное филе", amountPerBaseServing: 350),
            SeedIngredient(product: "Яйца куриные", amountPerBaseServing: 1),
            SeedIngredient(product: "Мука пшеничная", amountPerBaseServing: 40),
            SeedIngredient(product: "Соль", amountPerBaseServing: 3),
            SeedIngredient(product: "Растительное масло", amountPerBaseServing: 40),
        ]),
        SeedRecipe(name: "Салат с сыром и огурцами", cookingTimeMinutes: 10, baseServings: 2, ingredients: [
            SeedIngredient(product: "Сыр твёрдый (голландский)", amountPerBaseServing: 100),
            SeedIngredient(product: "Огурцы", amountPerBaseServing: 150),
            SeedIngredient(product: "Укроп", amountPerBaseServing: 5),
            SeedIngredient(product: "Майонез", amountPerBaseServing: 30),
        ]),
        SeedRecipe(name: "Макароны по-флотски", cookingTimeMinutes: 30, baseServings: 2, ingredients: [
            SeedIngredient(product: "Макароны (сухие)", amountPerBaseServing: 200),
            SeedIngredient(product: "Говяжий фарш (15% жирности)", amountPerBaseServing: 250),
            SeedIngredient(product: "Лук репчатый", amountPerBaseServing: 50),
            SeedIngredient(product: "Соль", amountPerBaseServing: 3),
            SeedIngredient(product: "Растительное масло", amountPerBaseServing: 15),
        ]),
        SeedRecipe(name: "Гренки с чесноком", cookingTimeMinutes: 10, baseServings: 2, ingredients: [
            SeedIngredient(product: "Хлеб пшеничный", amountPerBaseServing: 150),
            SeedIngredient(product: "Чеснок", amountPerBaseServing: 10),
            SeedIngredient(product: "Растительное масло", amountPerBaseServing: 30),
            SeedIngredient(product: "Соль", amountPerBaseServing: 2),
        ]),
        SeedRecipe(name: "Овощное рагу", cookingTimeMinutes: 35, baseServings: 2, ingredients: [
            SeedIngredient(product: "Картофель", amountPerBaseServing: 250),
            SeedIngredient(product: "Морковь", amountPerBaseServing: 80),
            SeedIngredient(product: "Лук репчатый", amountPerBaseServing: 60),
            SeedIngredient(product: "Болгарский перец", amountPerBaseServing: 100),
            SeedIngredient(product: "Помидоры", amountPerBaseServing: 100),
            SeedIngredient(product: "Растительное масло", amountPerBaseServing: 20),
            SeedIngredient(product: "Соль", amountPerBaseServing: 4),
        ]),
        SeedRecipe(name: "Куриная грудка гриль с лимоном", cookingTimeMinutes: 20, baseServings: 2, ingredients: [
            SeedIngredient(product: "Куриное филе", amountPerBaseServing: 350),
            SeedIngredient(product: "Лимон", amountPerBaseServing: 0.5),
            SeedIngredient(product: "Чеснок", amountPerBaseServing: 10),
            SeedIngredient(product: "Растительное масло", amountPerBaseServing: 15),
            SeedIngredient(product: "Соль", amountPerBaseServing: 3),
        ]),
        SeedRecipe(name: "Яблочные оладьи", cookingTimeMinutes: 20, baseServings: 2, ingredients: [
            SeedIngredient(product: "Яблоко", amountPerBaseServing: 2),
            SeedIngredient(product: "Мука пшеничная", amountPerBaseServing: 100),
            SeedIngredient(product: "Яйца куриные", amountPerBaseServing: 1),
            SeedIngredient(product: "Сахар", amountPerBaseServing: 30),
            SeedIngredient(product: "Растительное масло", amountPerBaseServing: 30),
        ]),
        SeedRecipe(name: "Котлеты из свиного фарша", cookingTimeMinutes: 30, baseServings: 2, ingredients: [
            SeedIngredient(product: "Фарш свиной", amountPerBaseServing: 400),
            SeedIngredient(product: "Лук репчатый", amountPerBaseServing: 50),
            SeedIngredient(product: "Яйца куриные", amountPerBaseServing: 1),
            SeedIngredient(product: "Соль", amountPerBaseServing: 3),
            SeedIngredient(product: "Растительное масло", amountPerBaseServing: 20),
        ]),
        SeedRecipe(name: "Домашние котлеты микс (свинина-говядина)", cookingTimeMinutes: 35, baseServings: 2, ingredients: [
            SeedIngredient(product: "Фарш свино-говяжий (50/50)", amountPerBaseServing: 400),
            SeedIngredient(product: "Лук репчатый", amountPerBaseServing: 60),
            SeedIngredient(product: "Яйца куриные", amountPerBaseServing: 1),
            SeedIngredient(product: "Хлеб пшеничный", amountPerBaseServing: 40),
            SeedIngredient(product: "Молоко 2.5%", amountPerBaseServing: 40),
            SeedIngredient(product: "Соль", amountPerBaseServing: 3),
        ]),
        SeedRecipe(name: "Сырная тарелка", cookingTimeMinutes: 10, baseServings: 2, ingredients: [
            SeedIngredient(product: "Сыр Дор Блю (голубой)", amountPerBaseServing: 50),
            SeedIngredient(product: "Сыр твёрдый (голландский)", amountPerBaseServing: 50),
            SeedIngredient(product: "Сыр сливочный (крем-сыр)", amountPerBaseServing: 50),
            SeedIngredient(product: "Хлеб Бородинский", amountPerBaseServing: 60),
        ]),
        SeedRecipe(name: "Бутерброд со сливочным сыром и зеленью", cookingTimeMinutes: 5, baseServings: 2, ingredients: [
            SeedIngredient(product: "Хлеб чёрный (ржаной)", amountPerBaseServing: 80),
            SeedIngredient(product: "Сыр сливочный (крем-сыр)", amountPerBaseServing: 60),
            SeedIngredient(product: "Укроп", amountPerBaseServing: 5),
            SeedIngredient(product: "Огурцы", amountPerBaseServing: 50),
        ]),
        SeedRecipe(name: "Горячий бутерброд с плавленым сыром", cookingTimeMinutes: 10, baseServings: 2, ingredients: [
            SeedIngredient(product: "Хлеб Бородинский", amountPerBaseServing: 80),
            SeedIngredient(product: "Сыр плавленый", amountPerBaseServing: 60),
            SeedIngredient(product: "Сливочное масло", amountPerBaseServing: 10),
        ]),
        SeedRecipe(name: "Стейк из говяжьей вырезки", cookingTimeMinutes: 20, baseServings: 2, ingredients: [
            SeedIngredient(product: "Говяжья вырезка (без жира)", amountPerBaseServing: 350),
            SeedIngredient(product: "Растительное масло", amountPerBaseServing: 15),
            SeedIngredient(product: "Соль", amountPerBaseServing: 3),
            SeedIngredient(product: "Чеснок", amountPerBaseServing: 10),
        ]),
        SeedRecipe(name: "Куриные бёдра запечённые с чесноком", cookingTimeMinutes: 40, baseServings: 2, ingredients: [
            SeedIngredient(product: "Куриные бёдра", amountPerBaseServing: 500),
            SeedIngredient(product: "Чеснок", amountPerBaseServing: 15),
            SeedIngredient(product: "Растительное масло", amountPerBaseServing: 20),
            SeedIngredient(product: "Соль", amountPerBaseServing: 4),
        ]),
        SeedRecipe(name: "Куриные окорочка жареные с луком", cookingTimeMinutes: 35, baseServings: 2, ingredients: [
            SeedIngredient(product: "Куриные окорочка", amountPerBaseServing: 500),
            SeedIngredient(product: "Лук репчатый", amountPerBaseServing: 80),
            SeedIngredient(product: "Растительное масло", amountPerBaseServing: 20),
            SeedIngredient(product: "Соль", amountPerBaseServing: 4),
        ]),
        SeedRecipe(name: "Куриная голень тушёная с овощами", cookingTimeMinutes: 40, baseServings: 2, ingredients: [
            SeedIngredient(product: "Куриная голень", amountPerBaseServing: 450),
            SeedIngredient(product: "Морковь", amountPerBaseServing: 60),
            SeedIngredient(product: "Лук репчатый", amountPerBaseServing: 60),
            SeedIngredient(product: "Помидоры", amountPerBaseServing: 100),
            SeedIngredient(product: "Растительное масло", amountPerBaseServing: 15),
            SeedIngredient(product: "Соль", amountPerBaseServing: 4),
        ]),
        SeedRecipe(name: "Салат с айсбергом и курицей", cookingTimeMinutes: 20, baseServings: 2, ingredients: [
            SeedIngredient(product: "Салат Айсберг", amountPerBaseServing: 200),
            SeedIngredient(product: "Куриное филе", amountPerBaseServing: 250),
            SeedIngredient(product: "Сыр твёрдый (голландский)", amountPerBaseServing: 50),
            SeedIngredient(product: "Помидоры", amountPerBaseServing: 100),
            SeedIngredient(product: "Майонез", amountPerBaseServing: 30),
        ]),
        SeedRecipe(name: "Форель, запечённая с лимоном", cookingTimeMinutes: 25, baseServings: 2, ingredients: [
            SeedIngredient(product: "Форель охлаждённая", amountPerBaseServing: 350),
            SeedIngredient(product: "Лимон", amountPerBaseServing: 0.5),
            SeedIngredient(product: "Укроп", amountPerBaseServing: 5),
            SeedIngredient(product: "Растительное масло", amountPerBaseServing: 15),
            SeedIngredient(product: "Соль", amountPerBaseServing: 3),
        ]),
        SeedRecipe(name: "Креветки жареные с чесноком", cookingTimeMinutes: 15, baseServings: 2, ingredients: [
            SeedIngredient(product: "Креветки (очищенные)", amountPerBaseServing: 300),
            SeedIngredient(product: "Чеснок", amountPerBaseServing: 15),
            SeedIngredient(product: "Растительное масло", amountPerBaseServing: 20),
            SeedIngredient(product: "Соль", amountPerBaseServing: 3),
        ]),
        SeedRecipe(name: "Салат с креветками и айсбергом", cookingTimeMinutes: 15, baseServings: 2, ingredients: [
            SeedIngredient(product: "Креветки (очищенные)", amountPerBaseServing: 200),
            SeedIngredient(product: "Салат Айсберг", amountPerBaseServing: 150),
            SeedIngredient(product: "Огурцы", amountPerBaseServing: 100),
            SeedIngredient(product: "Майонез", amountPerBaseServing: 30),
        ]),
        SeedRecipe(name: "Паста с креветками в сливочном соусе", cookingTimeMinutes: 25, baseServings: 2, ingredients: [
            SeedIngredient(product: "Макароны (сухие)", amountPerBaseServing: 200),
            SeedIngredient(product: "Креветки (очищенные)", amountPerBaseServing: 250),
            SeedIngredient(product: "Сыр сливочный (крем-сыр)", amountPerBaseServing: 100),
            SeedIngredient(product: "Чеснок", amountPerBaseServing: 10),
            SeedIngredient(product: "Растительное масло", amountPerBaseServing: 15),
        ]),
        SeedRecipe(name: "Индейка (филе) запечённая", cookingTimeMinutes: 35, baseServings: 2, ingredients: [
            SeedIngredient(product: "Индейка (филе грудки)", amountPerBaseServing: 400),
            SeedIngredient(product: "Растительное масло", amountPerBaseServing: 15),
            SeedIngredient(product: "Соль", amountPerBaseServing: 3),
            SeedIngredient(product: "Чеснок", amountPerBaseServing: 10),
        ]),
        SeedRecipe(name: "Индейка (бедро), тушёная с овощами", cookingTimeMinutes: 40, baseServings: 2, ingredients: [
            SeedIngredient(product: "Индейка (бедро)", amountPerBaseServing: 400),
            SeedIngredient(product: "Морковь", amountPerBaseServing: 60),
            SeedIngredient(product: "Лук репчатый", amountPerBaseServing: 60),
            SeedIngredient(product: "Помидоры", amountPerBaseServing: 100),
            SeedIngredient(product: "Растительное масло", amountPerBaseServing: 15),
        ]),
        SeedRecipe(name: "Ролл-шаурма с индейкой в лаваше", cookingTimeMinutes: 15, baseServings: 2, ingredients: [
            SeedIngredient(product: "Лаваш/пита", amountPerBaseServing: 150),
            SeedIngredient(product: "Индейка (филе грудки)", amountPerBaseServing: 250),
            SeedIngredient(product: "Огурцы маринованные", amountPerBaseServing: 60),
            SeedIngredient(product: "Салат Айсберг", amountPerBaseServing: 50),
            SeedIngredient(product: "Кетчуп", amountPerBaseServing: 30),
            SeedIngredient(product: "Майонез", amountPerBaseServing: 20),
        ]),
        SeedRecipe(name: "Сэндвич с индейкой и сыром на Бородинском", cookingTimeMinutes: 10, baseServings: 2, ingredients: [
            SeedIngredient(product: "Хлеб Бородинский", amountPerBaseServing: 100),
            SeedIngredient(product: "Индейка (филе грудки)", amountPerBaseServing: 150),
            SeedIngredient(product: "Сыр твёрдый (голландский)", amountPerBaseServing: 60),
            SeedIngredient(product: "Огурцы маринованные", amountPerBaseServing: 40),
            SeedIngredient(product: "Кетчуп", amountPerBaseServing: 20),
        ]),
        SeedRecipe(name: "Бутерброд с форелью и сливочным сыром", cookingTimeMinutes: 10, baseServings: 2, ingredients: [
            SeedIngredient(product: "Хлеб чёрный (ржаной)", amountPerBaseServing: 80),
            SeedIngredient(product: "Форель охлаждённая", amountPerBaseServing: 100),
            SeedIngredient(product: "Сыр сливочный (крем-сыр)", amountPerBaseServing: 50),
            SeedIngredient(product: "Огурцы", amountPerBaseServing: 40),
            SeedIngredient(product: "Укроп", amountPerBaseServing: 3),
        ]),
        SeedRecipe(name: "Форель с рисом и овощами", cookingTimeMinutes: 30, baseServings: 2, ingredients: [
            SeedIngredient(product: "Форель охлаждённая", amountPerBaseServing: 300),
            SeedIngredient(product: "Рис (сухой)", amountPerBaseServing: 100),
            SeedIngredient(product: "Морковь", amountPerBaseServing: 50),
            SeedIngredient(product: "Лимон", amountPerBaseServing: 0.3),
        ]),
    ]
}
